# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jekyll-time-to-read
- jemoji

# Site settings
url: 'https://www.quinn.mx'
baseurl: ''
title: Quinn Daley
description: 'Wool-gatherings about Leeds, sewing, music, politics, gender, language & tech. Eventually. Promise.'
permalink: pretty
logo: "/assets/quinn.jpg"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
  Blog: /
  'About me': /about/
  Contact: /contact/

# Collections
collections:
  posts:
    title: 'Quinn Peeks: a blog'
    short_title: Blog
    description: |
      Wool-gatherings about Leeds, sewing, music, politics, gender, language & tech. Eventually. Promise.
    output: true
    feature_image: "/assets/leeds.jpg"
