# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jekyll-time-to-read
- jemoji

# Site settings
url: 'https://www.quinn.mx'
baseurl: ''
title: 'Quinn Peaks'
description: Quinn Daley's obligatory brain dump
permalink: pretty
logo: "/assets/quinn.jpg"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
  Home: /
  'About me': /about/

# Footer nav
navigation_footer:
  Back to top: "#top"

# Collections
collections:
  posts:
    title: Blog
    description: |
      Hello there!
    output: true
    feature_image: "/assets/leeds.jpg"
