# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jekyll-time-to-read
- jemoji
- jekyll-responsive-image

# Site settings
url: 'https://www.quinn.mx'
baseurl: ''
title: Quinn Daley
description: 'Wool-gatherings about Leeds, sewing, music, politics, gender, language & tech. Eventually. Promise.'
permalink: pretty
logo: "/assets/quinn.jpg"
avatarurl: "/assets/logos/logo@32px.png"
disqus: quinnmx
google_analytics: 'UA-139304439-1'

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
  - title: Blog
    url: /
  - title: About me
    url: /about/
  - title: Contact
    url: /contact/

# Collections
collections:
  posts:
    title: 'Quinn Peeks: a blog'
    short_title: Blog
    description: |
      Wool-gatherings about Leeds, sewing, music, politics, gender, language & tech. Eventually. Promise.
    output: true
    feature_image: "/assets/leeds.jpg"

favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/logo@16px.png'
  32: '/assets/logos/logo@32px.png'
  96: '/assets/logos/logo@96px.png'
  120: '/assets/logos/logo@120px.png'
  144: '/assets/logos/logo@144px.png'
  180: '/assets/logos/logo@180px.png'
  512: '/assets/logos/logo@512px.png'
  1024: '/assets/logos/logo@1024px.png'
manifest:
  theme_color: '#a33a83'
  short_name: 'Quinn.mx'
responsive_image:
  template: _includes/responsive-image.html
  sizes:
    - width: 400
    - width: 744
